name: investec_open_api
description: Dart implementation for Investecs Open API (http://openapi.investec.com)

version: 0.1.0-nullsafety

version: 0.2.0+1

repository: https://github.com/RemeJuan/investec_open_api_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

scripts: derry.yaml

dependencies:
  equatable: ^2.0.0
  http: ^0.13.0
  universal_io: ^2.0.0

dev_dependencies:
  test: 1.16.2
  mockito: 5.0.1
  pedantic: 1.11.0
  build_runner:
