name: investec_open_api
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0-nullsafety.3
  http: ^0.13.0
  universal_io: ^2.0.0-nullsafety.2

dev_dependencies:
  test: ^1.16.2
  mockito: ^5.0.0-nullsafety.7
  pedantic: ^1.10.0
  build_runner:
