// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in investec_open_api/test/domain/usecases/get_account_balance_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:investec_open_api/domain/entities/account_balance_entity.dart'
    as _i2;
import 'package:investec_open_api/domain/repositories/account_balance_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeAccountBalanceEntity extends _i1.Fake
    implements _i2.AccountBalanceEntity {}

/// A class which mocks [AccountBalanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountBalanceRepository extends _i1.Mock
    implements _i3.AccountBalanceRepository {
  MockAccountBalanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccountBalanceEntity> getBalance(String? accountId) =>
      (super.noSuchMethod(Invocation.method(#getBalance, [accountId]),
              returnValue: Future.value(_FakeAccountBalanceEntity()))
          as _i4.Future<_i2.AccountBalanceEntity>);
}
